# main text of home
name: Alex Naka
bio: (Neuro)science, data, code, that sort of thing. 

# twitter summary info
description: (Neuro)science, data, code, that sort of thing.

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/patchemall.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-external: false
resume-url: https://google.com/?q=my+resume

title: ANaka/ANaka.github.io
repository: ANaka/ANaka.github.io

url: https://anaka.github.io
# your url: http://USERNAME.github.io

permalink: /:title/

# To enable google analytics, supply your token below
analytics-google: 'UA-142673814-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: anaka-github-io # enter this from your disqus account
  categories: [blog] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
# facebook: myfacebook
twitter: gottapatchemall
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: alex-naka
# youtube: myyoutube
# spotify: myspotify
github: anaka
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
# email: myemail@gmail.com

authors:
    alexnaka:
        name: Alex Naka
        bio: 
        external-image: false
        picture: assets/images/profile.jpg
        twitter: gottapatchemall

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: false
publications: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

kramdown:
  math_engine: mathjax

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com

compress_html:
    ignore:
        envs:
        - development
        - stage

exclude: ["travis.sh", "Rakefile", "README.md", "Gemfile", "Gemfile.lock", "FAQ.md"]

collections:
  - pubs

